sudo: required
services:
    - docker

script:
    - docker build -t drissboumlik/node .
    - docker images drissboumlik/node

before_deploy:
    - docker login -u drissboumlik -p corticothropine

deply:
    provider: script
    script: docker push drissboumlik/node
    on:
        branch: master